'use strict';

//=========================================================================================================================================
//This data quizzes users about the countyName of a townName within the UK.
//Data for this list came from: http://whitefiles.org/b4_g/5_town_to_counties_index/
//=========================================================================================================================================

module.exports = {
  "DATA" : [
    {townName: "Aberdare", countyName: "Mid Glamorgan"},
    {townName: "Aberdeen", countyName: "Aberdeenshire"},
    {townName: "Aberdovey", countyName: "Gwynedd"},
    {townName: "Abergavenny", countyName: "Gwent"},
    {townName: "Abergele", countyName: "Clwyd"},
    {townName: "Abertillery", countyName: "Gwent"},
    {townName: "Aberystwyth", countyName: "Dyfed"},
    {townName: "Abingdon", countyName: "Oxfordshire"},
    {townName: "Accrington", countyName: "Lancashire"},
    {townName: "Airdrie", countyName: "Lanarkshire"},
    {townName: "Alcester", countyName: "Warwickshire"},
    {townName: "Aldeburgh", countyName: "Suffolk"},
    {townName: "Alderley Edge", countyName: "Cheshire"},
    {townName: "Aldershot", countyName: "Hampshire"},
    {townName: "Alfreton", countyName: "Derbyshire"},
    {townName: "Alness", countyName: "Ross-shire"},
    {townName: "Alnwick", countyName: "Northumberland"},
    {townName: "Alresford", countyName: "Hampshire"},
    {townName: "Alston", countyName: "Cumbria"},
    {townName: "Alton", countyName: "Hampshire"},
    {townName: "Altrincham", countyName: "Cheshire"},
    {townName: "Ambleside", countyName: "Cumbria"},
    {townName: "Amersham", countyName: "Buckinghamshire"},
    {townName: "Amesbury", countyName: "Wiltshire"},
    {townName: "Ammanford", countyName: "Carmarthenshire"},
    {townName: "Andover", countyName: "Hampshire"},
    {townName: "Anstruther", countyName: "Fife"},
    {townName: "Antrim", countyName: "Co Antrim"},
    {townName: "Appleby-in-Westmorland", countyName: "Cumbria"},
    {townName: "Arbroath", countyName: "Angus"},
    {townName: "Ardrossan", countyName: "Ayrshire"},
    {townName: "Armagh", countyName: "Co Armagh"},
    {townName: "Arthog", countyName: "Gwynedd"},
    {townName: "Arundel", countyName: "West Sussex"},
    {townName: "Ascot", countyName: "Berkshire"},
    {townName: "Ashbourne", countyName: "Derbyshire"},
    {townName: "Ashburton", countyName: "Devon"},
    {townName: "Ashford", countyName: "Kent"},
    {townName: "Ashford", countyName: "Middlesex"},
    {townName: "Ashington", countyName: "Northumberland"},
    {townName: "Ashtead", countyName: "Surrey"},
    {townName: "Ashton-under-Lyne", countyName: "Greater Manchester"},
    {townName: "Attleborough", countyName: "Norfolk"},
    {townName: "Aviemore", countyName: "Inverness-shire"},
    {townName: "Axminster", countyName: "Devon"},
    {townName: "Aylesbury", countyName: "Buckinghamshire"},
    {townName: "Ayr", countyName: "Ayrshire"},
    {townName: "Bala", countyName: "Gwynedd"},
    {townName: "Baldock", countyName: "Hertfordshire"},
    {townName: "Ballachulish", countyName: "Argyll"},
    {townName: "Ballycastle", countyName: "Co Antrim"},
    {townName: "Ballyclare", countyName: "Co Antrim"},
    {townName: "Ballymena", countyName: "Co Antrim"},
    {townName: "Ballymoney", countyName: "Co Antrim"},
    {townName: "Bamburgh", countyName: "Northumberland"},
    {townName: "Bamstaple", countyName: "Devon"},
    {townName: "Banbridge", countyName: "Co Down"},
    {townName: "Banbury", countyName: "Oxfordshire"},
    {townName: "Banchory", countyName: "Kincardineshire"},
    {townName: "Banff", countyName: "Aberdeenshire"},
    {townName: "Bangor", countyName: "Co Down"},
    {townName: "Bangor", countyName: "Gwynedd"},
    {townName: "Banstead", countyName: "Surrey"},
    {townName: "Barking", countyName: "Essex"},
    {townName: "Barmouth", countyName: "Gwynedd"},
    {townName: "Barnard Castle", countyName: "Co Durham"},
    {townName: "Barnet", countyName: "Hertfordshire"},
    {townName: "Barnsley", countyName: "South Yorkshire"},
    {townName: "Barnstaple", countyName: "Devon"},
    {townName: "Barry", countyName: "South Glamorgan"},
    {townName: "Barrow-in Furness", countyName: "Cumbria"},
    {townName: "Barton-upon-Humber", countyName: "South Humberside"},
    {townName: "Basildon", countyName: "Essex"},
    {townName: "Basingstoke", countyName: "Hampshire"},
    {townName: "Bath", countyName: "Avon"},
    {townName: "Bathgate", countyName: "West Lothian"},
    {townName: "Battle", countyName: "East Sussex"},
    {townName: "Beaumaris", countyName: "Gwynedd"},
    {townName: "Beccles", countyName: "Suffolk"},
    {townName: "Beckenham", countyName: "Kent"},
    {townName: "Bedale", countyName: "North Yorkshire"},
    {townName: "Bedford", countyName: "Bedfordshire"},
    {townName: "Belfast", countyName: "Belfast"},
    {townName: "Belvedere", countyName: "Kent"},
    {townName: "Benneet", countyName: "Essex"},
    {townName: "Berkhamsted", countyName: "Hertfordshire"},
    {townName: "Berwick-on-Tweed", countyName: "Northumberland"},
    {townName: "Betws-y-Coed", countyName: "Conwy"},
    {townName: "Beverley", countyName: "North Humberside"},
    {townName: "Bewdley", countyName: "Worcestershire"},
    {townName: "Bexhill-on-Sea", countyName: "East Sussex"},
    {townName: "Bicester", countyName: "Oxfordshire"},
    {townName: "Bideford", countyName: "Devon"},
    {townName: "Biggar", countyName: "Lanarkshire"},
    {townName: "Biggleswade", countyName: "Bedfordshire"},
    {townName: "Billericay", countyName: "Essex"},
    {townName: "Billingshurst", countyName: "West Sussex"},
    {townName: "Bingley", countyName: "West Yorkshire"},
    {townName: "Birkenhead", countyName: "Merseyside"},
    {townName: "Birmingham", countyName: "West Midlands"},
    {townName: "Bishop Auckland", countyName: "Co Durham"},
    {townName: "Bishops Castle", countyName: "Shropshire"},
    {townName: "Bishop's Stortford", countyName: "Hertfordshire"},
    {townName: "Bishops Waltham", countyName: "Hampshire"},
    {townName: "Blackburn", countyName: "Lancashire"},
    {townName: "Blackpool", countyName: "Lancashire"},
    {townName: "Blaenau Ffestiniog", countyName: "Gwynedd"},
    {townName: "Blairgowrie", countyName: "Perthshire"},
    {townName: "Blandford Forum", countyName: "Dorset"},
    {townName: "Blaydon-on-Tyne", countyName: "Tyne and Wear"},
    {townName: "Bodmin", countyName: "Cornwall"},
    {townName: "Bognor Regis", countyName: "West Sussex"},
    {townName: "Boldon Colliery", countyName: "Tyne and Wear"},
    {townName: "Bolton", countyName: "Lancashire"},
    {townName: "Bonnyrigg", countyName: "Midlothian"},
    {townName: "Bootle", countyName: "Merseyside"},
    {townName: "Bordon", countyName: "Hampshire"},
    {townName: "Borehamwood", countyName: "Hertfordshire"},
    {townName: "Boston", countyName: "Lincolnshire"},
    {townName: "Botness", countyName: "West Lothian"},
    {townName: "Bourne", countyName: "Lincolnshire"},
    {townName: "Bournemouth", countyName: "Dorset"},
    {townName: "Brackley", countyName: "Northamptonshire"},
    {townName: "Bracknell", countyName: "Berkshire"},
    {townName: "Bradford", countyName: "West Yorkshire"},
    {townName: "Braintree", countyName: "Essex"},
    {townName: "Brampton", countyName: "Cumbria"},
    {townName: "Braunton", countyName: "Devon"},
    {townName: "Brecon", countyName: "Powys"},
    {townName: "Brentford", countyName: "Middlesex"},
    {townName: "Brentwood", countyName: "Essex"},
    {townName: "Bridgend", countyName: "Mid Glamorgan"},
    {townName: "Bridgnorth", countyName: "Shropshire"},
    {townName: "Bridgwater", countyName: "Somerset"},
    {townName: "Bridlington", countyName: "North Humberside"},
    {townName: "Bridport", countyName: "Dorset"},
    {townName: "Brigg", countyName: "Lincolnshire"},
    {townName: "Brighouse", countyName: "West Yorkshire"},
    {townName: "Brighton", countyName: "East Sussex"},
    {townName: "Bristol", countyName: "Avon"},
    {townName: "Brixham", countyName: "Devon"},
    {townName: "Broadford", countyName: "Isle of Skye"},
    {townName: "Broadstairs", countyName: "Kent"},
    {townName: "Broadway", countyName: "Hereford and Worcester"},
    {townName: "Brockenhurst", countyName: "Hampshire"},
    {townName: "Brodick", countyName: "Isle of Arran"},
    {townName: "Bromley", countyName: "Kent"},
    {townName: "Bromsgrove", countyName: "Hereford and Worcester"},
    {townName: "Brooke", countyName: "Norfolk"},
    {townName: "Broxburn", countyName: "West Lothian"},
    {townName: "Buckfastleigh", countyName: "Devon"},
    {townName: "Buckhurst Hill", countyName: "Essex"},
    {townName: "Buckie", countyName: "Banffshire"},
    {townName: "Buckingham", countyName: "Buckinghamshire"},
    {townName: "Bude", countyName: "Cornwall"},
    {townName: "Budleigh Salterton", countyName: "Devon"},
    {townName: "Builth Wells", countyName: "Powys"},
    {townName: "Bunessan", countyName: "Isle of Mull"},
    {townName: "Bungay", countyName: "Suffolk"},
    {townName: "Burgess Hill", countyName: "West Sussex"},
    {townName: "Burnham-on-Sea", countyName: "Somerset"},
    {townName: "Burnley", countyName: "Lancashire"},
    {townName: "Burton-on-Trent", countyName: "Staffordshire"},
    {townName: "Bury", countyName: "Lancashire"},
    {townName: "Bury St Edmunds", countyName: "Suffolk"},
    {townName: "Bushmills", countyName: "Co Antrim"},
    {townName: "Buxton", countyName: "Derbyshire"},
    {townName: "Caernarvon", countyName: "Gwynedd"},
    {townName: "Caerphilly", countyName: "Mid Glamorgan"},
    {townName: "Calne", countyName: "Wiltshire"},
    {townName: "Camberley", countyName: "Surrey"},
    {townName: "Cambridge", countyName: "Cambridgeshire"},
    {townName: "Camelford", countyName: "Cornwall"},
    {townName: "CampbeltownName", countyName: "Argyll"},
    {townName: "Cannock", countyName: "Staffordshire"},
    {townName: "Canterbury", countyName: "Kent"},
    {townName: "Cardiff", countyName: "South Glamorgan"},
    {townName: "Cardigan", countyName: "Dyfed"},
    {townName: "Carlisle", countyName: "Cumbria"},
    {townName: "Carloway", countyName: "Isle of Lewis"},
    {townName: "Carluke", countyName: "Lanarkshire"},
    {townName: "Carmarthen", countyName: "Dyfed"},
    {townName: "Carnforth", countyName: "Lancashire"},
    {townName: "Carrickfergus", countyName: "Co Antrim"},
    {townName: "Carshalton", countyName: "Surrey"},
    {townName: "Castle Douglas", countyName: "Kirkcudbrightshire"},
    {townName: "Castlederg", countyName: "Co Tyrone"},
    {townName: "CastletownName", countyName: "Isle of Man"},
    {townName: "Castlewellan", countyName: "Co Down"},
    {townName: "Caterham", countyName: "Surrey"},
    {townName: "Cemmaes Bay", countyName: "Gwynedd"},
    {townName: "Cemmaes Road", countyName: "Gwynedd"},
    {townName: "Cerne Abbas", countyName: "Dorset"},
    {townName: "Chard", countyName: "Somerset"},
    {townName: "Chatham", countyName: "Kent"},
    {townName: "Chatteris", countyName: "Cambridgeshire"},
    {townName: "Cheadle", countyName: "Cheshire"},
    {townName: "Cheam", countyName: "Surrey"},
    {townName: "Cheddar", countyName: "Somerset"},
    {townName: "Chelmsford", countyName: "Essex"},
    {townName: "Cheltenham", countyName: "Gloucestershire"},
    {townName: "Chepstow", countyName: "Gwent"},
    {townName: "Chertsey", countyName: "Surrey"},
    {townName: "Chesham", countyName: "Buckinghamshire"},
    {townName: "Chester", countyName: "Cheshire"},
    {townName: "Chester-le-Street", countyName: "Co Durham"},
    {townName: "Chesterfield", countyName: "Derbyshire"},
    {townName: "Chichester", countyName: "West Sussex"},
    {townName: "Chippenham", countyName: "Wiltshire"},
    {townName: "Chipping Norton", countyName: "Oxfordshire"},
    {townName: "Chipping Sodbury", countyName: "Gloucestershire"},
    {townName: "Chorley", countyName: "Lancashire"},
    {townName: "Christchurch", countyName: "Dorset"},
    {townName: "Church Stretton", countyName: "Shropshire"},
    {townName: "Cinderford", countyName: "Gloucestershne"},
    {townName: "Cirencester", countyName: "Gloucestershire"},
    {townName: "Clacton-on-Sea", countyName: "Essex"},
    {townName: "Cleethorpes", countyName: "South Humberside"},
    {townName: "Clevedon", countyName: "Avon"},
    {townName: "Clitheroe", countyName: "Lancashire"},
    {townName: "Clogher", countyName: "Co Tyrone"},
    {townName: "Clopton", countyName: "Northamptonshire"},
    {townName: "Coalville", countyName: "Leicestershire"},
    {townName: "Coatbridge", countyName: "Lanarkshire"},
    {townName: "Cobham", countyName: "Surrey"},
    {townName: "Cockermouth", countyName: "Cumbria"},
    {townName: "Colchester", countyName: "Essex"},
    {townName: "Coleshill", countyName: "Warwickshire"},
    {townName: "Coleraine", countyName: "Co Londonderry"},
    {townName: "Colwyn Bay", countyName: "Clwyd"},
    {townName: "Congleton", countyName: "Cheshire"},
    {townName: "Coniston", countyName: "Cumbria"},
    {townName: "Consett", countyName: "Co Durham"},
    {townName: "Conwy", countyName: "Gwynedd"},
    {townName: "CookstownName", countyName: "Co Tyrone"},
    {townName: "Coppull", countyName: "Lancashire"},
    {townName: "Corbridge", countyName: "Northumberland"},
    {townName: "Corby", countyName: "Northamptonshire"},
    {townName: "Corwen", countyName: "Clwyd"},
    {townName: "Coulsdon", countyName: "Surrey"},
    {townName: "Coventry", countyName: "West Midlands"},
    {townName: "Craigavon", countyName: "Co Armagh"},
    {townName: "Cramlington", countyName: "Northumberland"},
    {townName: "Cranbrook", countyName: "Kent"},
    {townName: "Cranleigh", countyName: "Surrey"},
    {townName: "Craven Arms", countyName: "Shropshire"},
    {townName: "Crawley", countyName: "West Sussex"},
    {townName: "Crediton", countyName: "Devon"},
    {townName: "Crewe", countyName: "Cheshire"},
    {townName: "Crieff", countyName: "Perthshire"},
    {townName: "Cromer", countyName: "Norfolk"},
    {townName: "Crowborough", countyName: "East Sussex"},
    {townName: "Croy", countyName: "Inverness-shire"},
    {townName: "Croydon", countyName: "Surrey"},
    {townName: "Crumlin", countyName: "Co Antrim"},
    {townName: "Cullompton", countyName: "Devon"},
    {townName: "Cumnock", countyName: "East Ayrshire"},
    {townName: "Cupar", countyName: "Fife"},
    {townName: "Cwmbran", countyName: "Gwent"},
    {townName: "Dagenham", countyName: "Essex"},
    {townName: "Dalbeattie", countyName: "Kirkcudbrightshire"},
    {townName: "Dalmally", countyName: "Argyll"},
    {townName: "Dalry", countyName: "Ayrshire"},
    {townName: "Darlington", countyName: "Co Durham"},
    {townName: "Dartford", countyName: "Kent"},
    {townName: "Darvel", countyName: "Ayrshire"},
    {townName: "Daventry", countyName: "Northamptonshire"},
    {townName: "Deal", countyName: "Kent"},
    {townName: "Deeside", countyName: "Clwyd"},
    {townName: "Derby", countyName: "Derbyshire"},
    {townName: "Dereham", countyName: "Norfolk"},
    {townName: "Devizes", countyName: "Wiltshire"},
    {townName: "Dewsbury", countyName: "West Yorkshire"},
    {townName: "Didcot", countyName: "Oxfordshire"},
    {townName: "Dinas Powis", countyName: "South Glamorgan"},
    {townName: "Dingwall", countyName: "Ross-shire"},
    {townName: "Diss", countyName: "Norfolk"},
    {townName: "Dolgellau", countyName: "Gwynedd"},
    {townName: "Doncaster", countyName: "South Yorkshire"},
    {townName: "Dorchester", countyName: "Dorset"},
    {townName: "Dorking", countyName: "Surrey"},
    {townName: "Dornoch", countyName: "Sutherland"},
    {townName: "Douglas", countyName: "Isle of Man"},
    {townName: "Dover", countyName: "Kent"},
    {townName: "Downham Market", countyName: "Norfolk"},
    {townName: "Downpatrick", countyName: "Co Down"},
    {townName: "Driffield", countyName: "North Humberside"},
    {townName: "Droitwich", countyName: "Hereford and Worcester"},
    {townName: "Dromore", countyName: "Co Down"},
    {townName: "Dudley", countyName: "West Midlands"},
    {townName: "Dulverton", countyName: "Somerset"},
    {townName: "Dumbarton", countyName: "Dunbartonshire"},
    {townName: "Dumfries", countyName: "Dumfriesshire"},
    {townName: "Dunbar", countyName: "East Lothian"},
    {townName: "Dunblane", countyName: "Perthshire"},
    {townName: "Dundee", countyName: "Angus"},
    {townName: "Dunfermline", countyName: "Fife"},
    {townName: "Dungannon", countyName: "Co Tyrone"},
    {townName: "Dunkeld", countyName: "Perthshire"},
    {townName: "Dunmow", countyName: "Essex"},
    {townName: "Dunmurry", countyName: "Belfast"},
    {townName: "Dunoon", countyName: "Argyll"},
    {townName: "Duns", countyName: "Berwickshire"},
    {townName: "Dunstable", countyName: "Bedfordshire"},
    {townName: "Durham", countyName: "Co Durham"},
    {townName: "Dursley", countyName: "Gloucestershire"},
    {townName: "Easingwold", countyName: "North Yorkshire"},
    {townName: "East Grinstead", countyName: "West Sussex"},
    {townName: "East Kilbride", countyName: "South Lanarkshire"},
    {townName: "East Molesey", countyName: "Surrey"},
    {townName: "Eastbourne", countyName: "East Sussex"},
    {townName: "Eastleigh", countyName: "Hampshire"},
    {townName: "Ebbsfleet", countyName: "Kent"},
    {townName: "Ebbw Vale", countyName: "Gwent"},
    {townName: "Edenbridge", countyName: "Kent"},
    {townName: "Edgware", countyName: "Middlesex"},
    {townName: "Edinburgh", countyName: "Edinburgh"},
    {townName: "Egham", countyName: "Surrey"},
    {townName: "Elgin", countyName: "Morayshire"},
    {townName: "Ellesmere Port", countyName: "Cheshire"},
    {townName: "Ellon", countyName: "Aberdeenshire"},
    {townName: "Ely", countyName: "Cambridgeshire"},
    {townName: "Emsworth", countyName: "Hampshire"},
    {townName: "Enfeld", countyName: "Middlesex"},
    {townName: "Enniskillen", countyName: "Co Fermanagh"},
    {townName: "Epping", countyName: "Essex"},
    {townName: "Epsom", countyName: "Surrey"},
    {townName: "Erith", countyName: "Kent"},
    {townName: "Esher", countyName: "Surrey"},
    {townName: "Evesham", countyName: "Worcestershire"},
    {townName: "Exeter", countyName: "Devon"},
    {townName: "Exmouth", countyName: "Devon"},
    {townName: "Fakenham", countyName: "Norfolk"},
    {townName: "Falkirk", countyName: "Stirlingshire"},
    {townName: "Falmouth", countyName: "Cornwall"},
    {townName: "Fareham", countyName: "Hampshire"},
    {townName: "Faringdon", countyName: "Oxfordshire"},
    {townName: "Farnborough", countyName: "Hampshire"},
    {townName: "Farnham", countyName: "Surrey"},
    {townName: "Felixstowe", countyName: "Suffolk"},
    {townName: "Fishguard", countyName: "Dyfed"},
    {townName: "FivemiletownName", countyName: "Co Tyrone"},
    {townName: "Fleet", countyName: "Hampshire"},
    {townName: "Fleetwood", countyName: "Lancashire"},
    {townName: "Flint", countyName: "Clwyd"},
    {townName: "Folkestone", countyName: "Kent"},
    {townName: "Forfar", countyName: "Angus"},
    {townName: "Fort William", countyName: "Inverness-shire"},
    {townName: "Fortrose", countyName: "Ross-shire"},
    {townName: "Fowey", countyName: "Cornwall"},
    {townName: "Fraserburgh", countyName: "Aberdeenshire"},
    {townName: "Freshwater", countyName: "Isle of Wight"},
    {townName: "Frinton-on-Sea", countyName: "Essex"},
    {townName: "Frome", countyName: "Somerset"},
    {townName: "Gainsborough", countyName: "Lincolnshire"},
    {townName: "Gairloch", countyName: "Ross-shire"},
    {townName: "Galasheils", countyName: "Selkirkshire"},
    {townName: "Garstang", countyName: "Lancashire"},
    {townName: "Gateshead", countyName: "Tyne and Wear"},
    {townName: "Gerrards Cross", countyName: "Buckinghamshire"},
    {townName: "Gillingham", countyName: "Dorset"},
    {townName: "Gillingham", countyName: "Kent"},
    {townName: "Girvan", countyName: "South Ayrshire"},
    {townName: "Glamorgan", countyName: "Rotherham"},
    {townName: "Glasgow", countyName: "Glasgow"},
    {townName: "Glastonbury", countyName: "Somerset"},
    {townName: "Glenrothes", countyName: "Fife"},
    {townName: "Glossop", countyName: "Derbyshire"},
    {townName: "Gloucester", countyName: "Gloucestershire"},
    {townName: "Godalming", countyName: "Surrey"},
    {townName: "Godstone", countyName: "Surrey"},
    {townName: "Goole", countyName: "East Riding of Yorkshire"},
    {townName: "Gosforth", countyName: "Cumbria"},
    {townName: "Gosport", countyName: "Hampshire"},
    {townName: "Grange-over-Sands", countyName: "Cumbria"},
    {townName: "Grangemouth", countyName: "Midlothian"},
    {townName: "Grantham", countyName: "Lincolnshire"},
    {townName: "Gravesend", countyName: "Kent"},
    {townName: "Grays Thurrock", countyName: "Essex"},
    {townName: "Great Dunmow", countyName: "Essex"},
    {townName: "Great Missenden", countyName: "Buckinghamshire"},
    {townName: "Great Yarmouth", countyName: "Norfolk"},
    {townName: "Greenford", countyName: "Middlesex"},
    {townName: "Greenock", countyName: "Renfrewshire"},
    {townName: "Gretna", countyName: "Dumfriesshire"},
    {townName: "Grimsby", countyName: "South Humberside"},
    {townName: "Guernsey", countyName: "Channel Islands"},
    {townName: "Guildford", countyName: "Surrey"},
    {townName: "Guisborough", countyName: "North Yorkshire"},
    {townName: "Guiseley", countyName: "West Yorkshire"},
    {townName: "Gullane", countyName: "East Lothian"},
    {townName: "Hamilton", countyName: "Lanark shire"},
    {townName: "Haddington", countyName: "East Lothian"},
    {townName: "Hailsham", countyName: "East Sussex"},
    {townName: "Halesowen", countyName: "West Midlands"},
    {townName: "Halifax", countyName: "West Yorkshire"},
    {townName: "Halstead", countyName: "Essex"},
    {townName: "Haltwhistle", countyName: "Northumberland"},
    {townName: "Hampton", countyName: "Middlesex"},
    {townName: "Harlow", countyName: "Essex"},
    {townName: "Harpenden", countyName: "Hertfordshire"},
    {townName: "Harrogate", countyName: "North Yorkshire"},
    {townName: "Harrow", countyName: "Middlesex"},
    {townName: "Hartlepool", countyName: "Cleveland"},
    {townName: "Harwich", countyName: "Essex"},
    {townName: "Haslemere", countyName: "Surrey"},
    {townName: "Hassocks", countyName: "West Sussex"},
    {townName: "Hastings", countyName: "East Sussex"},
    {townName: "Hatfield", countyName: "Hertfordshire"},
    {townName: "Hathersage", countyName: "Derbyshire"},
    {townName: "Havant", countyName: "Hampshire"},
    {townName: "Haverfordwest", countyName: "Pembrokeshire"},
    {townName: "Haverhill", countyName: "Suffolk"},
    {townName: "Hawick", countyName: "Roxburghshire"},
    {townName: "Hawkshead", countyName: "Cumbria"},
    {townName: "Hay-on-Wye", countyName: "Powys"},
    {townName: "Hayes", countyName: "Middlesex"},
    {townName: "Hayling Island", countyName: "Hampshire"},
    {townName: "Haywards Heath", countyName: "West Sussex"},
    {townName: "Heanor", countyName: "Derbyshire"},
    {townName: "Heathfield", countyName: "East Sussex"},
    {townName: "Helensburgh", countyName: "Dunbartonshire"},
    {townName: "Helmsley", countyName: "North Yorkshire"},
    {townName: "Helston", countyName: "Cornwall"},
    {townName: "Hemel Hempstead", countyName: "Hertfordshire"},
    {townName: "Henfield", countyName: "West Sussex"},
    {townName: "Henley-on-Thames", countyName: "Oxfordshire"},
    {townName: "Hereford", countyName: "Hereford and Worcester"},
    {townName: "Herne Bay", countyName: "Kent"},
    {townName: "Hertford", countyName: "Hertfordshire"},
    {townName: "Hessle", countyName: "North Humberside"},
    {townName: "Hexham", countyName: "Northumberland"},
    {townName: "Heywood", countyName: "Lancashire"},
    {townName: "High Wycombe", countyName: "Buckinghamshire"},
    {townName: "Highbridge", countyName: "Somerset"},
    {townName: "Hillsborough", countyName: "Co Down"},
    {townName: "Hinckley", countyName: "Leicestershire"},
    {townName: "Hindhead", countyName: "Surrey"},
    {townName: "Hitchin", countyName: "Hertfordshire"},
    {townName: "Hockley", countyName: "Essex"},
    {townName: "Hoddesdon", countyName: "Hertfordshire"},
    {townName: "Holbeach", countyName: "Lincolnshire"},
    {townName: "Holmes Chapel", countyName: "Cheshire"},
    {townName: "Holsworthy", countyName: "Devon"},
    {townName: "Holt", countyName: "Norfolk"},
    {townName: "Holyhead", countyName: "Gwynedd"},
    {townName: "Holywood", countyName: "Co Down"},
    {townName: "Honington", countyName: "Lincolnshire"},
    {townName: "Honiton", countyName: "Devon"},
    {townName: "Hook", countyName: "Hampshire"},
    {townName: "Horley", countyName: "Surrey"},
    {townName: "Hornby", countyName: "Lancashire"},
    {townName: "Hornchurch", countyName: "Essex"},
    {townName: "Hornsea", countyName: "East Riding of Yorkshire"},
    {townName: "Horsham", countyName: "West Sussex"},
    {townName: "Houghton le Spring", countyName: "Tyne and Wear"},
    {townName: "Hounslow", countyName: "Middlesex"},
    {townName: "Hove", countyName: "East Sussex"},
    {townName: "Huddersfield", countyName: "West Yorkshire"},
    {townName: "Hull", countyName: "North Humberside"},
    {townName: "Hungerford", countyName: "Berkshire"},
    {townName: "Hunstanton", countyName: "Norfolk"},
    {townName: "Huntingdon", countyName: "Cambridgeshire"},
    {townName: "Huntly", countyName: "Aberdeenshire"},
    {townName: "Hyde", countyName: "Cheshire"},
    {townName: "Hythe", countyName: "Kent"},
    {townName: "Ilford", countyName: "Essex"},
    {townName: "Ilfracombe", countyName: "Devon"},
    {townName: "Ilkeston", countyName: "Derbyshire"},
    {townName: "Ilkley", countyName: "West Yorkshire"},
    {townName: "Immingham", countyName: "South Humberside"},
    {townName: "Ingatestone", countyName: "Essex"},
    {townName: "Insch", countyName: "Aberdeenshire"},
    {townName: "Inveraray", countyName: "Argyll"},
    {townName: "Inverness", countyName: "Inverness-shire"},
    {townName: "Inverurie", countyName: "Aberdeenshire"},
    {townName: "Iona", countyName: "Isle of Iona"},
    {townName: "Ipstones", countyName: "Staffordshire"},
    {townName: "Ipswich", countyName: "Suffolk"},
    {townName: "Ironbridge", countyName: "Shropshire"},
    {townName: "Isle of Wight", countyName: "Isle of Wight"},
    {townName: "Isleworth", countyName: "Middlesex"},
    {townName: "Jersey", countyName: "Channel Islands"},
    {townName: "Johnstone", countyName: "Renfrewshire"},
    {townName: "Keighley", countyName: "West Yorkshire"},
    {townName: "Kelso", countyName: "Roxburghshire"},
    {townName: "Kendal", countyName: "Cumbria"},
    {townName: "Kenilworth", countyName: "Warwickshire"},
    {townName: "Keswick", countyName: "Cumbria"},
    {townName: "Kettering", countyName: "Northamptonshire"},
    {townName: "Kidderminster", countyName: "Hereford and Worcester"},
    {townName: "Kilbirnie", countyName: "Ayrshire"},
    {townName: "Killin", countyName: "Perthshire"},
    {townName: "Killingholme", countyName: "Lincolnshire"},
    {townName: "Kilmacolm", countyName: "Renfrewshire"},
    {townName: "Kilmarnock", countyName: "Ayrshire"},
    {townName: "King's Lynn", countyName: "Norfolk"},
    {townName: "Kings Langley", countyName: "Hertfordshire"},
    {townName: "Kingsbridge", countyName: "Devon"},
    {townName: "Kingston upon Thames", countyName: "Surrey"},
    {townName: "Kingswinford", countyName: "West Midlands"},
    {townName: "Kington", countyName: "Herefordshire"},
    {townName: "Kingussie", countyName: "Inverness-shire"},
    {townName: "Kirkby Stephen", countyName: "Cumbria"},
    {townName: "Kirkcaldy", countyName: "Fife"},
    {townName: "Kirkwhelpington", countyName: "Northumberland"},
    {townName: "Kirriemuir", countyName: "Angus"},
    {townName: "Knighton", countyName: "Powys"},
    {townName: "Knutsford", countyName: "Cheshire"},
    {townName: "Kyle", countyName: "Ross-shire"},
    {townName: "Kyleakin", countyName: "Isle of Skye"},
    {townName: "Laindon", countyName: "Essex"},
    {townName: "Lairg", countyName: "Sutherland"},
    {townName: "Lampeter", countyName: "Ceredigion"},
    {townName: "Lanark", countyName: "Lanarkshire"},
    {townName: "Lancaster", countyName: "Lancashire"},
    {townName: "Lancing", countyName: "West Sussex"},
    {townName: "Lapworth", countyName: "Warwickshire"},
    {townName: "Larbert", countyName: "Stirlingshire"},
    {townName: "Latheron", countyName: "Caithness"},
    {townName: "Launceston", countyName: "Cornwall"},
    {townName: "Leamington Spa", countyName: "Warwickshire"},
    {townName: "Leatherhead", countyName: "Surrey"},
    {townName: "Ledbury", countyName: "Hereford and Worcester"},
    {townName: "Leeds", countyName: "West Yorkshire"},
    {townName: "Leicester", countyName: "Leicestershire"},
    {townName: "Leigh", countyName: "Lancashire"},
    {townName: "Leigh-on-Sea", countyName: "Essex"},
    {townName: "Leighton Buzzard", countyName: "Bedfordshire"},
    {townName: "Leiston", countyName: "Suffolk"},
    {townName: "Leominster", countyName: "Hereford and Worcester"},
    {townName: "Lerwick", countyName: "Isle of Shetland"},
    {townName: "Letchworth", countyName: "Hertfordshire"},
    {townName: "Lewes", countyName: "East Sussex"},
    {townName: "Leyburn", countyName: "North Yorkshire"},
    {townName: "Leyland", countyName: "Lancashire"},
    {townName: "Lichfield", countyName: "Staffordshire"},
    {townName: "Lightwater", countyName: "Surrey"},
    {townName: "Limavady", countyName: "Co Londonderry"},
    {townName: "Lincoln", countyName: "Lincolnshire"},
    {townName: "Lingfield", countyName: "Surrey"},
    {townName: "Liphook", countyName: "Hampshire"},
    {townName: "Lisburn", countyName: "Co Antrim"},
    {townName: "Liskeard", countyName: "Cornwall"},
    {townName: "Liss", countyName: "Hampshire"},
    {townName: "Littleborough", countyName: "Lancashire"},
    {townName: "Littlehampton", countyName: "West Sussex"},
    {townName: "Liverpool", countyName: "Merseyside"},
    {townName: "Livingston", countyName: "West Lothian"},
    {townName: "Llanarth", countyName: "Ceredigion"},
    {townName: "Llanbedr", countyName: "Gwynedd"},
    {townName: "Llandeilo", countyName: "Carmarthenshire"},
    {townName: "Llandovery", countyName: "Carmarthenshire"},
    {townName: "Llandrindod Wells", countyName: "Powys"},
    {townName: "Llandudno", countyName: "Gwynedd"},
    {townName: "Llandysul", countyName: "Dyfed"},
    {townName: "Llanelli", countyName: "Dyfed"},
    {townName: "Llangollen", countyName: "Clwyd"},
    {townName: "Llanidloes", countyName: "Powys"},
    {townName: "Llanon", countyName: "Ceredigion"},
    {townName: "Llanrwst", countyName: "Gwynedd"},
    {townName: "Llantwit", countyName: "South Glamorgan"},
    {townName: "Llanwrda", countyName: "Dyfed"},
    {townName: "Llanwrtyd Wells", countyName: "Powys"},
    {townName: "Loanhead", countyName: "Midlothian"},
    {townName: "Lochboisdale", countyName: "Isle of Uist"},
    {townName: "Lochcarron", countyName: "Ross-shire"},
    {townName: "Lochgilphead", countyName: "Argyll"},
    {townName: "Lochwinnoch", countyName: "Renfrewshire"},
    {townName: "Lockerbie", countyName: "Dumfriesshire"},
    {townName: "London", countyName: "London"},
    {townName: "Londonderry", countyName: "Co Londonderry"},
    {townName: "Loughborough", countyName: "Leicestershire"},
    {townName: "Loughton", countyName: "Essex"},
    {townName: "Louth", countyName: "Lincolnshire"},
    {townName: "Lowestoft", countyName: "Suffolk"},
    {townName: "Ludlow", countyName: "Shropshire"},
    {townName: "Lurgan", countyName: "Co Antrim"},
    {townName: "Luton", countyName: "Bedfordshire"},
    {townName: "Lutterworth", countyName: "Leicestershire"},
    {townName: "Lydney", countyName: "Gloucestershire"},
    {townName: "Lymington", countyName: "Hampshire"},
    {townName: "Lyndhurst", countyName: "Hampshire"},
    {townName: "Lynton", countyName: "Devon"},
    {townName: "Lytham StAnnes", countyName: "Lancashire"},
    {townName: "Macclesfield", countyName: "Cheshire"},
    {townName: "Machynlleth", countyName: "Powys"},
    {townName: "Madingley", countyName: "Cambridgeshire"},
    {townName: "Maesteg", countyName: "Mid Glamorgan"},
    {townName: "Magharafelt", countyName: "Co Londonderry"},
    {townName: "Maidenhead", countyName: "Berkshire"},
    {townName: "Maidstone", countyName: "Kent"},
    {townName: "Maldon", countyName: "Essex"},
    {townName: "Malmesbury", countyName: "Wiltshire"},
    {townName: "Malpas", countyName: "Cheshire"},
    {townName: "Malton", countyName: "North Yorkshire"},
    {townName: "Malvern", countyName: "Hereford and Worcester"},
    {townName: "Manchester", countyName: "Greater Manchester"},
    {townName: "Mansfield", countyName: "Nottinghamshire"},
    {townName: "March", countyName: "Cambridgeshire"},
    {townName: "Margate", countyName: "Kent"},
    {townName: "Market Drayton", countyName: "Shropshire"},
    {townName: "Market Harborough", countyName: "Leicestershire"},
    {townName: "Market Rasen", countyName: "Lincolnshire"},
    {townName: "Market Weighton", countyName: "East Riding of Yorkshire"},
    {townName: "Marlborough", countyName: "Wiltshire"},
    {townName: "Marlow", countyName: "Buckinghamshire"},
    {townName: "Martin", countyName: "Lincolnshire"},
    {townName: "Maryport", countyName: "Cumbria"},
    {townName: "Matlock", countyName: "Derbyshire"},
    {townName: "Maud", countyName: "Aberdeenshire"},
    {townName: "Medway", countyName: "Kent"},
    {townName: "Meifod", countyName: "Powys"},
    {townName: "Melksham", countyName: "Wiltshire"},
    {townName: "Melton Mowbray", countyName: "Leicestershire"},
    {townName: "Mere", countyName: "Wiltshire"},
    {townName: "Meriden", countyName: "West Midlands"},
    {townName: "Merthyr Tydfil", countyName: "Mid Glamorgan"},
    {townName: "Mexborough", countyName: "South Yorkshire"},
    {townName: "Middlesbrough", countyName: "Cleveland"},
    {townName: "Middlewich", countyName: "Cheshire"},
    {townName: "Midhurst", countyName: "West Sussex"},
    {townName: "Mildenhall", countyName: "Suffolk"},
    {townName: "Milford Haven", countyName: "Pembrokeshire"},
    {townName: "Milton Keynes", countyName: "Buckinghamshire"},
    {townName: "Minehead", countyName: "Somerset"},
    {townName: "Mirfield", countyName: "West Yorkshire"},
    {townName: "Mitcham", countyName: "Surrey"},
    {townName: "Mitcheldean", countyName: "Gloucestershire"},
    {townName: "Mold", countyName: "Clwyd"},
    {townName: "Monmouth", countyName: "Gwent"},
    {townName: "Montgomery", countyName: "Powys"},
    {townName: "Montrose", countyName: "Angus"},
    {townName: "Morden", countyName: "Surrey"},
    {townName: "Morecambe", countyName: "Lancashire"},
    {townName: "Moretonhampstead", countyName: "Devon"},
    {townName: "Morpeth", countyName: "Northumberiand"},
    {townName: "Moscow", countyName: "East Ayrshire"},
    {townName: "Motherwell", countyName: "Lanarkshire"},
    {townName: "Musselburgh", countyName: "Midlothian"},
    {townName: "Nailsea", countyName: "Avon"},
    {townName: "Nairn", countyName: "Inverness-shire"},
    {townName: "Nantwich", countyName: "Cheshire"},
    {townName: "Narberth", countyName: "Pembrokeshire"},
    {townName: "Neath", countyName: "Neath Port Talbot"},
    {townName: "Nefyn", countyName: "Gwynedd"},
    {townName: "Nelson", countyName: "Lancashire"},
    {townName: "Nethy Bridge", countyName: "Inverness-shire"},
    {townName: "New Malden", countyName: "Surrey"},
    {townName: "New Mills", countyName: "Derbyshire"},
    {townName: "Newark", countyName: "Nottinghamshire"},
    {townName: "Newbury", countyName: "Berkshire"},
    {townName: "Newcastle", countyName: "Co Down"},
    {townName: "Newcastle", countyName: "Staffordshire"},
    {townName: "Newcastle Emlyn", countyName: "Dyfed"},
    {townName: "Newcastle upon Tyne", countyName: "Tyne and Wear"},
    {townName: "Newcastleton", countyName: "Roxburghshire"},
    {townName: "Newent", countyName: "Gloucestershire"},
    {townName: "Newhaven", countyName: "East Sussex"},
    {townName: "Newmarket", countyName: "Suffolk"},
    {townName: "Newport", countyName: "Gwent"},
    {townName: "Newport", countyName: "Isle of Wight"},
    {townName: "Newport", countyName: "Shropshire"},
    {townName: "Newport Pagnell", countyName: "Buckinghamshire"},
    {townName: "Newquay", countyName: "Cornwall"},
    {townName: "Newton Abbot", countyName: "Devon"},
    {townName: "NewtownName", countyName: "Powys"},
    {townName: "NewtownName-le- Willows", countyName: "Merseyside"},
    {townName: "NewtownNameabbey", countyName: "Co Antrim"},
    {townName: "NewtownNameards", countyName: "Co Down"},
    {townName: "North Berwick", countyName: "East Lothian"},
    {townName: "North Shields", countyName: "Tyne and Wear"},
    {townName: "North Walsham", countyName: "Norfolk"},
    {townName: "Northallerton", countyName: "North Yorkshire"},
    {townName: "Northampton", countyName: "Northamptonshire"},
    {townName: "Northwich", countyName: "Cheshire"},
    {townName: "Northwood", countyName: "Middlesex"},
    {townName: "Norwich", countyName: "Norfolk"},
    {townName: "Nottingham", countyName: "Nottinghamshire"},
    {townName: "Nottinghamshire", countyName: "Nottinghamshire"},
    {townName: "Nuneaton", countyName: "Warwickshire"},
    {townName: "Oakham", countyName: "Leicestershire"},
    {townName: "Oban", countyName: "Argyll"},
    {townName: "Okehampton", countyName: "Devon"},
    {townName: "Oldham", countyName: "Lancashire"},
    {townName: "Omagh", countyName: "Co Tyrone"},
    {townName: "Ongar", countyName: "Essex"},
    {townName: "Ormskirk", countyName: "Lancashire"},
    {townName: "Orpington", countyName: "Kent"},
    {townName: "Ossett", countyName: "West Yorkshire"},
    {townName: "Oswestry", countyName: "Shropshire"},
    {townName: "Otley", countyName: "West Yorkshire"},
    {townName: "Oxford", countyName: "Oxfordshire"},
    {townName: "Oxted", countyName: "Surrey"},
    {townName: "Paignton", countyName: "Devon"},
    {townName: "Paisley", countyName: "Renfrewshire"},
    {townName: "Pakenham", countyName: "Suffolk"},
    {townName: "Par", countyName: "Cornwall"},
    {townName: "Pembroke", countyName: "Dyfed"},
    {townName: "Penarth", countyName: "South Glamorgan"},
    {townName: "Pencombe", countyName: "Herefordshire"},
    {townName: "Penicuik", countyName: "Midlothian"},
    {townName: "Penmaenmawr", countyName: "Gwynedd"},
    {townName: "Penrhyndeudraeth", countyName: "Gwynedd"},
    {townName: "Penrith", countyName: "Cumbria"},
    {townName: "Penryn", countyName: "Cornwall"},
    {townName: "Penzance", countyName: "Cornwall"},
    {townName: "Pershore", countyName: "Hereford and Worcester"},
    {townName: "Perth", countyName: "Perthshire"},
    {townName: "Peterborough", countyName: "Cambridgeshire"},
    {townName: "Peterhead", countyName: "Aberdeenshire"},
    {townName: "Petersfield", countyName: "Hampshire"},
    {townName: "Petworth", countyName: "West Sussex"},
    {townName: "Pevensey", countyName: "East Sussex"},
    {townName: "Pewsey", countyName: "Wiltshire"},
    {townName: "Pickering", countyName: "North Yorkshire"},
    {townName: "Pinner", countyName: "Middlesex"},
    {townName: "Pitlochry", countyName: "Perthshire"},
    {townName: "Plymouth", countyName: "Devon"},
    {townName: "Pocklington", countyName: "East Riding of Yorkshire"},
    {townName: "Pontefract", countyName: "West Yorkshire"},
    {townName: "Pontyclun", countyName: "Mid Glamorgan"},
    {townName: "Pontypool", countyName: "Torfaen"},
    {townName: "Pontypridd", countyName: "Mid Glamorgan"},
    {townName: "Poole", countyName: "Dorset"},
    {townName: "Pooley Bridge", countyName: "Cumbria"},
    {townName: "Port Isaac", countyName: "Cornwall"},
    {townName: "Port Talbot", countyName: "West Glamorgan"},
    {townName: "Porthcawl", countyName: "Mid Glamorgan"},
    {townName: "Porthmadog", countyName: "Gwynedd"},
    {townName: "Portree", countyName: "Isle of Skye"},
    {townName: "Portrush", countyName: "Co Antrim"},
    {townName: "Portsmouth", countyName: "Hampshire"},
    {townName: "Potters Bar", countyName: "Hertfordshire"},
    {townName: "Poulton-le-Fylde", countyName: "Lancashire"},
    {townName: "Prescot", countyName: "Merseyside"},
    {townName: "Prestatyn", countyName: "Clwyd"},
    {townName: "Preston", countyName: "Lancashire"},
    {townName: "Prestwick", countyName: "Ayrshire"},
    {townName: "Princes Risborough", countyName: "Buckinghamshire"},
    {townName: "Prudhoe", countyName: "Northumberland"},
    {townName: "Pulborough", countyName: "West Sussex"},
    {townName: "Purley", countyName: "Surrey"},
    {townName: "Pwllheli", countyName: "Gwynedd"},
    {townName: "Radlett", countyName: "Hertfordshire"},
    {townName: "Ramsey", countyName: "Isle of Man"},
    {townName: "Ramsgate", countyName: "Kent"},
    {townName: "Raughton Head", countyName: "Cumbria"},
    {townName: "Rayleigh", countyName: "Essex"},
    {townName: "Reading", countyName: "Berkshire"},
    {townName: "Redcar", countyName: "Cleveland"},
    {townName: "Redditch", countyName: "Hereford and"},
    {townName: "Redhill", countyName: "Surrey"},
    {townName: "Redruth", countyName: "Cornwall"},
    {townName: "Reigate", countyName: "Surrey"},
    {townName: "Retford", countyName: "Nottmghamshire"},
    {townName: "Rhyl", countyName: "Clwyd"},
    {townName: "Richmond", countyName: "North Yorkshire"},
    {townName: "Richmond", countyName: "Surrey"},
    {townName: "Rickmansworth", countyName: "Hertfordshire"},
    {townName: "Riding Mill", countyName: "Northumberland"},
    {townName: "Ringwood", countyName: "Hampshire"},
    {townName: "Ripley", countyName: "Derbyshire"},
    {townName: "Ripon", countyName: "North Yorkshire"},
    {townName: "Robertsbridge", countyName: "East Sussex"},
    {townName: "Rochdale", countyName: "Lancashire"},
    {townName: "Rochester", countyName: "Kent"},
    {townName: "Rochford", countyName: "Essex"},
    {townName: "Rockbourne", countyName: "Hampshire"},
    {townName: "Romford", countyName: "Essex"},
    {townName: "Romsey", countyName: "Hampshire"},
    {townName: "Ross-on-Wye", countyName: "Herefordshire"},
    {townName: "Rossendale", countyName: "Lancashire"},
    {townName: "Rothbury", countyName: "Northumberland"},
    {townName: "Rotherham", countyName: "South Yorkshire"},
    {townName: "Rothesay", countyName: "Isle ofBute"},
    {townName: "Royston", countyName: "Hertfordshire"},
    {townName: "Rugby", countyName: "Warwickshire"},
    {townName: "Rugeley", countyName: "Staffordshire"},
    {townName: "Ruislip", countyName: "Middlesex"},
    {townName: "Runcorn", countyName: "Cheshire"},
    {townName: "Rushden", countyName: "Northamptonshire"},
    {townName: "Ruthin", countyName: "Clwyd"},
    {townName: "Rye", countyName: "East Sussex"},
    {townName: "Ryton", countyName: "Tyne and Wear"},
    {townName: "Saffron Walden", countyName: "Essex"},
    {townName: "Salford", countyName: "Lancashire"},
    {townName: "Salisbury", countyName: "Wiltshire"},
    {townName: "Saltash", countyName: "Cornwall"},
    {townName: "Saltburn-by-the-Sea", countyName: "Cleveland"},
    {townName: "Saltcoats", countyName: "Ayrshire"},
    {townName: "Sandbach", countyName: "Cheshire"},
    {townName: "Sandhurst", countyName: "Berkshire"},
    {townName: "Sandown", countyName: "Isle of Wight"},
    {townName: "Sandwich", countyName: "Kent"},
    {townName: "Sandy", countyName: "Bedfordshire"},
    {townName: "Sanquhar", countyName: "Dumfriesshire"},
    {townName: "Sawbridgeworth", countyName: "Hertfordshire"},
    {townName: "Saxmundham", countyName: "Suffolk"},
    {townName: "Scarborough", countyName: "North Yorkshire"},
    {townName: "Scarinish", countyName: "Isle of Tiree"},
    {townName: "Scunthorpe", countyName: "South Humberside"},
    {townName: "Seaford", countyName: "East Sussex"},
    {townName: "Seaham", countyName: "Co Durham"},
    {townName: "Seahouses", countyName: "Northumberland"},
    {townName: "Seaton", countyName: "Devon"},
    {townName: "Sedbergh", countyName: "Cumbria"},
    {townName: "Sedgefield", countyName: "Co Durham"},
    {townName: "Selby", countyName: "North Yorkshire"},
    {townName: "Selkirk", countyName: "Selkirkshire"},
    {townName: "Settle", countyName: "North Yorkshire"},
    {townName: "Sevenoaks", countyName: "Kent"},
    {townName: "Shaftesbury", countyName: "Wiltshire"},
    {townName: "Shap", countyName: "Cumbria"},
    {townName: "Shawbost", countyName: "Isle of Lewis"},
    {townName: "Sheffield", countyName: "South Yorkshire"},
    {townName: "Shepperton", countyName: "Middlesex"},
    {townName: "Shepton Mallet", countyName: "Somerset"},
    {townName: "Sherborne", countyName: "Dorset"},
    {townName: "Sheringham", countyName: "Norfolk"},
    {townName: "Shetland", countyName: "Isle of Shetland"},
    {townName: "Shifnal", countyName: "Shropshire"},
    {townName: "Shipley", countyName: "West Yorkshire"},
    {townName: "Shrewsbury", countyName: "Shropshire"},
    {townName: "Sidcup", countyName: "Kent"},
    {townName: "Sidmouth", countyName: "Devon"},
    {townName: "Sittingbourne", countyName: "Kent"},
    {townName: "Skegness", countyName: "Lincolnshire"},
    {townName: "Skelmersdale", countyName: "Lancashire"},
    {townName: "Skipton", countyName: "North Yorkshire"},
    {townName: "Sleaford", countyName: "Lincolnshire"},
    {townName: "Slough", countyName: "Berkshire"},
    {townName: "Solihull", countyName: "West Midlands"},
    {townName: "South Croydon", countyName: "Surrey"},
    {townName: "South Queensferry", countyName: "West Lothian"},
    {townName: "South Molton", countyName: "Devon"},
    {townName: "South Petherton", countyName: "Somerset"},
    {townName: "South Wirral", countyName: "Merseyside"},
    {townName: "Southall", countyName: "Middlesex"},
    {townName: "Southam", countyName: "Warwickshire"},
    {townName: "Southampton", countyName: "Hampshire"},
    {townName: "Southend-on-Sea", countyName: "Essex"},
    {townName: "Southminster", countyName: "Essex"},
    {townName: "Southport", countyName: "Merseyside"},
    {townName: "Southsea", countyName: "Hampshire"},
    {townName: "Southwell", countyName: "Nottinghamshire"},
    {townName: "Sowerby", countyName: "North Yorkshire"},
    {townName: "Spalding", countyName: "Lincolnshire"},
    {townName: "Spilsby", countyName: "Lincolnshire"},
    {townName: "St Albans", countyName: "Hertfordshire"},
    {townName: "St Andrews", countyName: "Fife"},
    {townName: "St Asaph", countyName: "Clwyd"},
    {townName: "St Austell", countyName: "Cornwall"},
    {townName: "St Clears", countyName: "Carmarthenshire"},
    {townName: "St Helens", countyName: "Merseyside"},
    {townName: "St Ives", countyName: "Cornwall"},
    {townName: "St Leonards-on-Sea", countyName: "East Sussex"},
    {townName: "Stafford", countyName: "Staffordshire"},
    {townName: "Staines", countyName: "Middlesex"},
    {townName: "Stamford", countyName: "Lincolnshire"},
    {townName: "Stanford-le-Hope", countyName: "Essex"},
    {townName: "Stanmore", countyName: "Middlesex"},
    {townName: "Stevenage", countyName: "Hertfordshire"},
    {townName: "Stirling", countyName: "Stirlingshire"},
    {townName: "Stockport", countyName: "Cheshire"},
    {townName: "Stocksfield", countyName: "Northumberland"},
    {townName: "Stockton-on-Tees", countyName: "Cleveland"},
    {townName: "Stoke-on-Trent", countyName: "Staffordshire"},
    {townName: "Stone", countyName: "Staffordshire"},
    {townName: "Stonehaven", countyName: "Kincardineshire"},
    {townName: "Stornoway", countyName: "Isle of Lewis"},
    {townName: "Stourbridge", countyName: "West Midlands"},
    {townName: "Stourport-on-Severn", countyName: "Hereford and Worcester"},
    {townName: "Stow-on-the-Wold", countyName: "Gloucestershire"},
    {townName: "Stowmarket", countyName: "Suffolk"},
    {townName: "Stranraer", countyName: "WigtownNameshire"},
    {townName: "Stratford-upon-Avon", countyName: "Warwickshire"},
    {townName: "Strathcarron", countyName: "Ross-shire"},
    {townName: "Strathaven", countyName: "South Lanarkshire"},
    {townName: "Strathpeffer", countyName: "Ross-shire"},
    {townName: "Street", countyName: "Somerset"},
    {townName: "Stroud", countyName: "Gloucestershire"},
    {townName: "Sudbury", countyName: "Suffolk"},
    {townName: "Sunbury-on-Thames", countyName: "Middlesex"},
    {townName: "Sunderland", countyName: "Tyne and Wear"},
    {townName: "Surbiton", countyName: "Surrey"},
    {townName: "Sutton", countyName: "Surrey"},
    {townName: "Sutton Coldfield", countyName: "West Midlands"},
    {townName: "Sutton-in-Ashfield", countyName: "Nottinghamshire"},
    {townName: "Swaffham", countyName: "Norfolk"},
    {townName: "Swanage", countyName: "Dorset"},
    {townName: "Swanley", countyName: "Kent"},
    {townName: "Swansea", countyName: "West Glamorgan"},
    {townName: "Swindon", countyName: "Wiltshire"},
    {townName: "Tain", countyName: "Ross-shire"},
    {townName: "Talybont", countyName: "Gwynedd"},
    {townName: "Tamworth", countyName: "Staffordshire"},
    {townName: "Tarbert", countyName: "Argyll"},
    {townName: "Tarporley", countyName: "Cheshire"},
    {townName: "Taunton", countyName: "Somerset"},
    {townName: "Tavistock", countyName: "Devon"},
    {townName: "Teddington", countyName: "Middlesex"},
    {townName: "Teignmouth", countyName: "Devon"},
    {townName: "Telford", countyName: "Shropshire"},
    {townName: "Temple Cloud", countyName: "Somerset"},
    {townName: "Templecombe", countyName: "Somerset"},
    {townName: "Tenby", countyName: "Dyfed"},
    {townName: "Tewkesbury", countyName: "Gloucestershire"},
    {townName: "Thame", countyName: "Oxfordshire"},
    {townName: "Thanet", countyName: "Kent"},
    {townName: "Thatcham", countyName: "Berkshire"},
    {townName: "Thetford", countyName: "Norfolk"},
    {townName: "Thirsk", countyName: "North Yorkshire"},
    {townName: "Thornton Heath", countyName: "Surrey"},
    {townName: "Thurso", countyName: "Caithness"},
    {townName: "Tilbury", countyName: "Essex"},
    {townName: "Tipton", countyName: "West Midlands"},
    {townName: "Tiverton", countyName: "Devon"},
    {townName: "Tonbridge", countyName: "Kent"},
    {townName: "Torquay", countyName: "Devon"},
    {townName: "Torrington", countyName: "Devon"},
    {townName: "Totland Bay", countyName: "Isle of Wight"},
    {townName: "Towcester", countyName: "Northamptonshire"},
    {townName: "Tranent", countyName: "East Lothian"},
    {townName: "Tredegar", countyName: "Gwent"},
    {townName: "Tring", countyName: "Hertfordshire"},
    {townName: "Trowbridge", countyName: "Wiltshire"},
    {townName: "Truro", countyName: "Cornwall"},
    {townName: "Tunbridge Wells", countyName: "Kent"},
    {townName: "Turriff", countyName: "Aberdeenshire"},
    {townName: "Twickenham", countyName: "Middlesex"},
    {townName: "Tywyn", countyName: "Gwynedd"},
    {townName: "Uckfield", countyName: "East Sussex"},
    {townName: "Ulverston", countyName: "Cumbria"},
    {townName: "Umberleigh", countyName: "Devon"},
    {townName: "Uttoxeter", countyName: "Staffordshire"},
    {townName: "Uxbridge", countyName: "Middlesex"},
    {townName: "Ventnor", countyName: "Isle ofWight"},
    {townName: "Wadebridge", countyName: "Cornwall"},
    {townName: "Wakefield", countyName: "West Yorkshire"},
    {townName: "Wallasey", countyName: "Merseyside"},
    {townName: "Wallingford", countyName: "Oxfordshire"},
    {townName: "Wallington", countyName: "Surrey"},
    {townName: "Walsall", countyName: "West Midlands"},
    {townName: "Walsingham", countyName: "Norfolk"},
    {townName: "Waltham Cross", countyName: "Hertfordshire"},
    {townName: "Walton on the Naze", countyName: "Essex"},
    {townName: "Walton-on-Thames", countyName: "Surrey"},
    {townName: "Wantage", countyName: "Oxfordshire"},
    {townName: "Warboys", countyName: "Cambridgeshire"},
    {townName: "Ware", countyName: "Hertfordshire"},
    {townName: "Wareham", countyName: "Dorset"},
    {townName: "Warley", countyName: "West Midlands"},
    {townName: "Warminster", countyName: "Wiltshire"},
    {townName: "Warrington", countyName: "Cheshire"},
    {townName: "Warwick", countyName: "Warwickshire"},
    {townName: "Warwickshire", countyName: "Warwickshire"},
    {townName: "Washington", countyName: "Tyne and Wear"},
    {townName: "Watchet", countyName: "Somerset"},
    {townName: "Watford", countyName: "Hertfordshire"},
    {townName: "Wedmore", countyName: "Somerset"},
    {townName: "Welling", countyName: "Kent"},
    {townName: "Wellingborough", countyName: "Northamptonshire"},
    {townName: "Wells", countyName: "Somerset"},
    {townName: "Wells-next-the-Sea", countyName: "Norfolk"},
    {townName: "Welshpool", countyName: "Powys"},
    {townName: "Welwyn", countyName: "Hertfordshire"},
    {townName: "Welwyn Garden City", countyName: "Hertfordshire"},
    {townName: "Wem", countyName: "Shropshire"},
    {townName: "Wembley", countyName: "Middlesex"},
    {townName: "West Bromwich", countyName: "West Midlands"},
    {townName: "West Byfleet", countyName: "Surrey"},
    {townName: "West Drayton", countyName: "Middlesex"},
    {townName: "West Heslerton", countyName: "North Yorkshire"},
    {townName: "West Kilbride", countyName: "Ayrshire"},
    {townName: "West Linton", countyName: "Peeblesshire"},
    {townName: "West Malling", countyName: "Kent"},
    {townName: "West Wickham", countyName: "Kent"},
    {townName: "Westbury", countyName: "Wiltshire"},
    {townName: "Westcliff-on-Sea", countyName: "Essex"},
    {townName: "Westerham", countyName: "Kent"},
    {townName: "Weston-super-Mare", countyName: "Avon"},
    {townName: "Wetherby", countyName: "West Yorkshire"},
    {townName: "Weybridge", countyName: "Surrey"},
    {townName: "Weymouth", countyName: "Dorset"},
    {townName: "Whatton", countyName: "Nottinghamshire"},
    {townName: "Whitby", countyName: "North Yorkshire"},
    {townName: "Whitchurch", countyName: "Hampshire"},
    {townName: "Whitchurch", countyName: "Shropshire"},
    {townName: "Whitehaven", countyName: "Cumbria"},
    {townName: "Whitland", countyName: "Dyfed"},
    {townName: "Whitley Bay", countyName: "Tyne and Wear"},
    {townName: "Whitstable", countyName: "Kent"},
    {townName: "Wick", countyName: "Caithness"},
    {townName: "Wickford", countyName: "Essex"},
    {townName: "Wigan", countyName: "Lancashire"},
    {townName: "Wigton", countyName: "Cumbria"},
    {townName: "Wilmslow", countyName: "Cheshire"},
    {townName: "Wimborne", countyName: "Dorset"},
    {townName: "Wincanton", countyName: "Somerset"},
    {townName: "Winchester", countyName: "Hampshire"},
    {townName: "Windermere", countyName: "Cumbria"},
    {townName: "Windsor", countyName: "Berkshire"},
    {townName: "Winscombe", countyName: "Somerset"},
    {townName: "Wirral", countyName: "Merseyside"},
    {townName: "Wisbech", countyName: "Cambridgeshire"},
    {townName: "Wishaw", countyName: "Lanarkshire"},
    {townName: "Witham", countyName: "Buckinghamshire"},
    {townName: "Witham", countyName: "Essex"},
    {townName: "Witney", countyName: "Oxfordshire"},
    {townName: "Woking", countyName: "Surrey"},
    {townName: "Wokingham", countyName: "Berkshire"},
    {townName: "Wolverhampton", countyName: "West Midlands"},
    {townName: "Woodford Green", countyName: "Essex"},
    {townName: "Worcester", countyName: "Hereford and Worcester"},
    {townName: "Workington", countyName: "Cumbria"},
    {townName: "Worksop", countyName: "Nottinghamshire"},
    {townName: "Wormbridge", countyName: "Herefordshire"},
    {townName: "Worthing", countyName: "West Sussex"},
    {townName: "Wotton-under-Edge", countyName: "Gloucestershire"},
    {townName: "Wrexham", countyName: "Clwyd"},
    {townName: "Wymondham", countyName: "Norfolk"},
    {townName: "Yateley", countyName: "Surrey"},
    {townName: "Yelverton", countyName: "Devon"},
    {townName: "Yeovil", countyName: "Somerset"},
    {townName: "York", countyName: "North Yorkshire"},
  ]
}